
import fs from "node:fs";
import path from "node:path";

const username = "CodeByAbi";
const token = process.env.GITHUB_TOKEN;
const timezone = "Asia/Jakarta";

if (!token) {
  throw new Error("GITHUB_TOKEN is missing.");
}

function getLocalDate(date = new Date()) {
  const parts = new Intl.DateTimeFormat("en-CA", {
    timeZone: timezone,
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).formatToParts(date);

  const values = Object.fromEntries(
    parts
      .filter((part) => part.type !== "literal")
      .map((part) => [part.type, part.value])
  );

  return `${values.year}-${values.month}-${values.day}`;
}

function shiftDate(dateString, offset) {
  const [year, month, day] = dateString.split("-").map(Number);
  const date = new Date(Date.UTC(year, month - 1, day + offset));
  return date.toISOString().slice(0, 10);
}

function escapeXml(value) {
  return String(value).replace(/[<>&"']/g, (char) => ({
    "<": "&lt;",
    ">": "&gt;",
    "&": "&amp;",
    '"': "&quot;",
    "'": "&apos;",
  })[char]);
}

function makeCard(title, items) {
  const height = Math.max(230, 135 + items.length * 55);

  const rows = items.map((item, index) => {
    const y = 95 + index * 55;

    return `
      <text x="30" y="${y}" fill="#a8b3c5" font-size="14">${escapeXml(item.label)}</text>
      <text x="430" y="${y}" text-anchor="end" fill="#ffffff" font-size="17" font-weight="700">${escapeXml(item.value)}</text>
    `;
  }).join("");

  return `
    <svg xmlns="http://www.w3.org/2000/svg" width="460" height="${height}" viewBox="0 0 460 ${height}">
      <rect width="460" height="${height}" rx="16" fill="#0d1117" stroke="#30363d"/>
      <text x="30" y="43" fill="#58a6ff" font-size="19" font-weight="700">${escapeXml(title)}</text>
      ${rows}
      <text x="30" y="${height - 16}" fill="#8b949e" font-size="11">Generated by GitHub Actions · ${timezone}</text>
    </svg>
  `;
}

async function githubGraphQL(query, variables = {}) {
  const response = await fetch("https://api.github.com/graphql", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${token}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ query, variables }),
  });

  const result = await response.json();

  if (!response.ok || result.errors?.length) {
    throw new Error(JSON.stringify(result.errors ?? result, null, 2));
  }

  return result.data;
}

async function main() {
  const today = getLocalDate();
  const fromDate = shiftDate(today, -364);

  // Contribution calendar for the last 365 days.
  const contributionQuery = `
    query($login: String!, $from: DateTime!, $to: DateTime!) {
      user(login: $login) {
        contributionsCollection(from: $from, to: $to) {
          contributionCalendar {
            weeks {
              contributionDays {
                date
                contributionCount
              }
            }
          }
        }
      }
    }
  `;

  const contributionData = await githubGraphQL(contributionQuery, {
    login: username,
    from: `${fromDate}T00:00:00+07:00`,
    to: `${today}T23:59:59+07:00`,
  });

  const calendar =
    contributionData.user.contributionsCollection.contributionCalendar;

  const recentDays = calendar.weeks
    .flatMap((week) => week.contributionDays)
    .filter((day) => day.date >= fromDate && day.date <= today)
    .sort((a, b) => a.date.localeCompare(b.date));

  if (recentDays.length === 0) {
    throw new Error("GitHub returned no contribution calendar days.");
  }

  const total = recentDays.reduce(
    (sum, day) => sum + day.contributionCount,
    0
  );

  const countByDate = new Map(
    recentDays.map((day) => [day.date, day.contributionCount])
  );

  // If today has no contributions yet, count the streak through yesterday.
  const streakEnd =
    (countByDate.get(today) ?? 0) > 0
      ? today
      : shiftDate(today, -1);

  let currentStreak = 0;

  if ((countByDate.get(streakEnd) ?? 0) > 0) {
    for (let date = streakEnd; ; date = shiftDate(date, -1)) {
      if ((countByDate.get(date) ?? 0) === 0) break;
      currentStreak++;
    }
  }

  let longestStreak = 0;
  let runningStreak = 0;

  for (const day of recentDays) {
    if (day.contributionCount > 0) {
      runningStreak++;
      longestStreak = Math.max(longestStreak, runningStreak);
    } else {
      runningStreak = 0;
    }
  }

  // Aggregate languages from up to 100 public, non-fork repositories.
  const languageQuery = `
    query($login: String!) {
      user(login: $login) {
        repositories(
          first: 100
          privacy: PUBLIC
          isFork: false
          ownerAffiliations: OWNER
          orderBy: { field: UPDATED_AT, direction: DESC }
        ) {
          nodes {
            name
            languages(first: 10, orderBy: { field: SIZE, direction: DESC }) {
              edges {
                size
                node {
                  name
                  color
                }
              }
            }
          }
        }
      }
    }
  `;

  const languageData = await githubGraphQL(languageQuery, {
    login: username,
  });

  const repositories = languageData.user.repositories.nodes;
  const languageTotals = new Map();
  let totalBytes = 0;

  for (const repo of repositories) {
    for (const edge of repo.languages.edges) {
      const name = edge.node.name;
      const previous = languageTotals.get(name) ?? {
        bytes: 0,
        color: edge.node.color || "#8b949e",
      };

      previous.bytes += edge.size;
      languageTotals.set(name, previous);
      totalBytes += edge.size;
    }
  }

  const topLanguages = [...languageTotals.entries()]
    .map(([name, data]) => ({
      label: name,
      value: totalBytes > 0
        ? `${((data.bytes / totalBytes) * 100).toFixed(1)}%`
        : "0.0%",
      bytes: data.bytes,
    }))
    .sort((a, b) => b.bytes - a.bytes)
    .slice(0, 5);

  fs.mkdirSync("profile", { recursive: true });

  fs.writeFileSync(
    path.join("profile", "stats.svg"),
    makeCard("GitHub Contributions", [
      {
        label: "Contributions · Last 365 Days",
        value: total.toLocaleString("en-US"),
      },
    ])
  );

  fs.writeFileSync(
    path.join("profile", "streak.svg"),
    makeCard("Contribution Streak", [
      { label: "Current Streak", value: `${currentStreak} days` },
      { label: "Longest · Last 365 Days", value: `${longestStreak} days` },
    ])
  );

  fs.writeFileSync(
    path.join("profile", "top-langs.svg"),
    makeCard(
      "Top Languages · Public Repositories",
      topLanguages.length > 0
        ? topLanguages.map(({ label, value }) => ({ label, value }))
        : [{ label: "No language data available", value: "—" }]
    )
  );

  console.log(`Updated statistics for ${username}`);
  console.log(`Contributions in last 365 days: ${total}`);
  console.log(`Current streak: ${currentStreak} days`);
  console.log(`Longest streak in last 365 days: ${longestStreak} days`);
  console.log(`Repositories analyzed: ${repositories.length}`);
  console.log("Top languages:", topLanguages.map((lang) => lang.label).join(", "));
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
